// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * BarData is the computed display payload sent to the frontend on each poll.
 */
export class BarData {
    /**
     * Creates a new BarData instance.
     * @param {Partial<BarData>} [$$source = {}] - The source object to create the BarData.
     */
    constructor($$source = {}) {
        if (!("accountName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accountName"] = "";
        }
        if (!("subscriptionType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subscriptionType"] = "";
        }
        if (!("periodMessages" in $$source)) {
            /**
             * Message-based usage (more intuitive than raw tokens)
             * @member
             * @type {number}
             */
            this["periodMessages"] = 0;
        }
        if (!("periodPercent" in $$source)) {
            /**
             * 0.0–1.0 when msgLimit > 0
             * @member
             * @type {number}
             */
            this["periodPercent"] = 0;
        }
        if (!("periodMsgLimit" in $$source)) {
            /**
             * 0 = no limit configured
             * @member
             * @type {number}
             */
            this["periodMsgLimit"] = 0;
        }
        if (!("lastDataLabel" in $$source)) {
            /**
             * Most recent day with data (stats-cache may lag several days)
             * "TODAY" or "5-21"
             * @member
             * @type {string}
             */
            this["lastDataLabel"] = "";
        }
        if (!("lastDataMsgs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastDataMsgs"] = 0;
        }
        if (!("hourlyPercent" in $$source)) {
            /**
             * 0.0–1.0; negative if unavailable
             * @member
             * @type {number}
             */
            this["hourlyPercent"] = 0;
        }
        if (!("hourlyResetIn" in $$source)) {
            /**
             * countdown to 5h reset
             * @member
             * @type {string}
             */
            this["hourlyResetIn"] = "";
        }
        if (!("resetIn" in $$source)) {
            /**
             * Other metrics
             * @member
             * @type {string}
             */
            this["resetIn"] = "";
        }
        if (!("primaryModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["primaryModel"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * BUSY / IDLE / OFFLINE
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("limitExceeded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["limitExceeded"] = false;
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * unix ms
             * @member
             * @type {number}
             */
            this["lastUpdated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BarData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BarData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BarData(/** @type {Partial<BarData>} */($$parsedSource));
    }
}
