// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as claude$0 from "./internal/claude/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "./internal/platform/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates queries the latest GitHub release and compares its tag to the
 * running version. Network/parse failures come back in Error rather than as a Go
 * error so the menu can always show a friendly line.
 * @returns {$CancellablePromise<$models.UpdateCheckResult>}
 */
export function CheckForUpdates() {
    return $Call.ByID(2675659504).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CloseBrandMenu hides the dropdown — called by the menu page after an action so
 * the window object is kept for an instant reopen.
 * @returns {$CancellablePromise<void>}
 */
export function CloseBrandMenu() {
    return $Call.ByID(1922934579);
}

/**
 * @returns {$CancellablePromise<claude$0.BarData | null>}
 */
export function GetBarData() {
    return $Call.ByID(1002198872).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Config>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UpdateCheckResult>}
 */
export function GetLastUpdateResult() {
    return $Call.ByID(2159480791).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<platform$0.MonitorInfo[]>}
 */
export function GetMonitors() {
    return $Call.ByID(3692271108).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetPushdownStats returns active diagnostics for macOS window pushdown.
 * @returns {$CancellablePromise<platform$0.PushdownStats>}
 */
export function GetPushdownStats() {
    return $Call.ByID(2130621354).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * @param {string} downloadURL
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate(downloadURL) {
    return $Call.ByID(2443992793, downloadURL);
}

/**
 * OpenSettings opens the unified settings window (on the Accounts section). The
 * window's left-sidebar nav lets the user move to Stations / Bar Options from
 * there — replacing the old per-feature tray items.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(2024983644);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenUpdateWindow() {
    return $Call.ByID(1491903660);
}

/**
 * ParseStationItem classifies a single URL/ID into a StationItem for the
 * stations editor (so URL parsing stays authoritative on the Go side).
 * @param {string} input
 * @returns {$CancellablePromise<config$0.StationItem>}
 */
export function ParseStationItem(input) {
    return $Call.ByID(1591082711, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3181047470);
}

/**
 * RadioNext skips to the next track in the active station's queue. It's a no-op
 * when the radio is disabled or nothing has been queued yet (e.g. never played).
 * The bar's › track button drives this; it's grayed out for single-track and
 * livestream stations where there's nothing to step through.
 * @returns {$CancellablePromise<void>}
 */
export function RadioNext() {
    return $Call.ByID(4232239333);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RadioPause() {
    return $Call.ByID(1036964326);
}

/**
 * RadioPlayStation starts (or resumes) the configured station at index. The
 * station player owns the queue, shuffle, auto-advance and looping; it drives
 * the single-track audio controller one track at a time.
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function RadioPlayStation(index) {
    return $Call.ByID(1061425594, index);
}

/**
 * RadioPrev steps back to the previous track in the active station's queue. It's
 * a no-op when the radio is disabled or nothing has been queued yet. The bar's ‹
 * track button drives this.
 * @returns {$CancellablePromise<void>}
 */
export function RadioPrev() {
    return $Call.ByID(1848533721);
}

/**
 * RadioSeek jumps the currently-playing track to the given offset in seconds.
 * Driven by the bar's seek timeline. No-op when radio is disabled or nothing is
 * loaded; ignored for livestreams by the underlying player.
 * @param {number} seconds
 * @returns {$CancellablePromise<void>}
 */
export function RadioSeek(seconds) {
    return $Call.ByID(3754337124, seconds);
}

/**
 * RadioSetShuffle toggles shuffle mode for the station at index, persists it to
 * config, and applies it live to the station engine. It is a pure mode toggle:
 * it changes only the random-order setting and never starts or jumps playback,
 * so toggling while paused stays paused. The bar's shuffle button drives this
 * (the setting was removed from the stations editor).
 * @param {number} index
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function RadioSetShuffle(index, on) {
    return $Call.ByID(2403727805, index, on);
}

/**
 * @param {number} v
 * @returns {$CancellablePromise<void>}
 */
export function RadioSetVolume(v) {
    return $Call.ByID(3673750934, v);
}

/**
 * RadioStationHasTracks reports whether the station at index has more than one
 * track to step through, so the bar can enable/gray-out its ‹ › track buttons.
 * It's derived from config alone (no playback or network) and recognises
 * playlists even when an item's saved kind is a stale "video" hint — e.g. a
 * watch?v=…&list=… URL. Out-of-range indexes return false.
 * @param {number} index
 * @returns {$CancellablePromise<boolean>}
 */
export function RadioStationHasTracks(index) {
    return $Call.ByID(3726821172, index);
}

/**
 * @param {config$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3442292638, cfg);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveAccount(index) {
    return $Call.ByID(4119675500, index);
}

/**
 * SetActiveStation persists which station is selected in the bar cycler. It
 * does not start playback (use RadioPlayStation for that).
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveStation(index) {
    return $Call.ByID(3286258115, index);
}

/**
 * SetEditorOpen forces the bar fully expanded while the inline accounts editor
 * is shown (the editor is launched from the tray with the cursor off-bar, and
 * must stay open until dismissed). On close, the controller re-evaluates based
 * on the current cursor position.
 * @param {boolean} open
 * @returns {$CancellablePromise<void>}
 */
export function SetEditorOpen(open) {
    return $Call.ByID(3883131646, open);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function SetMonitor(index) {
    return $Call.ByID(2062485563, index);
}

/**
 * @param {number} opacity
 * @returns {$CancellablePromise<void>}
 */
export function SetOpacity(opacity) {
    return $Call.ByID(2521718736, opacity);
}

/**
 * @param {boolean} pinned
 * @returns {$CancellablePromise<void>}
 */
export function SetPinned(pinned) {
    return $Call.ByID(721057701, pinned);
}

/**
 * ToggleBrandMenu opens the small dropdown anchored under the ClawdPanel brand
 * icon, or closes it if it's already open. Like the settings popup it's a
 * separate frameless window — the 28-px bar has no room to draw a menu and clips
 * its own overflow. Created lazily, hidden (not destroyed) on close, and
 * auto-hidden the moment it loses focus so clicking elsewhere dismisses it.
 * 
 * The toggle has to survive a race: clicking the icon while the menu is open
 * first defocuses the menu (auto-hide) and only then delivers the click here, so
 * a plain "show if hidden" would always reopen. menuVisible answers "is it up
 * right now", and menuHiddenAt lets us recognise the auto-hide that this very
 * click just triggered and stay closed.
 * @returns {$CancellablePromise<void>}
 */
export function ToggleBrandMenu() {
    return $Call.ByID(2718533905);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleClickThrough() {
    return $Call.ByID(2867525164);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ToggleStartup() {
    return $Call.ByID(3862563746);
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
const $$createType1 = claude$0.BarData.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = config$0.Config.createFrom;
const $$createType4 = platform$0.MonitorInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = platform$0.PushdownStats.createFrom;
const $$createType7 = config$0.StationItem.createFrom;
