// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * UpdateCheckResult is returned to the brand menu's "Check for updates" item.
 * On failure Error carries a short message; otherwise the frontend compares
 * Current/Latest and opens URL when UpdateAvailable.
 */
export class UpdateCheckResult {
    /**
     * Creates a new UpdateCheckResult instance.
     * @param {Partial<UpdateCheckResult>} [$$source = {}] - The source object to create the UpdateCheckResult.
     */
    constructor($$source = {}) {
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateAvailable"] = false;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("changelog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["changelog"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateCheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCheckResult(/** @type {Partial<UpdateCheckResult>} */($$parsedSource));
    }
}
