// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * MonitorInfo is the app-facing monitor descriptor, exposed to the frontend.
 * Fields are identical across platforms; per-OS implementations populate them
 * from their native display APIs.
 */
export class MonitorInfo {
    /**
     * Creates a new MonitorInfo instance.
     * @param {Partial<MonitorInfo>} [$$source = {}] - The source object to create the MonitorInfo.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("left" in $$source)) {
            /**
             * physical pixels
             * @member
             * @type {number}
             */
            this["left"] = 0;
        }
        if (!("top" in $$source)) {
            /**
             * physical pixels
             * @member
             * @type {number}
             */
            this["top"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * logical pixels
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * logical pixels
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("physWidth" in $$source)) {
            /**
             * physical pixels (use for OS-native sizing calls)
             * @member
             * @type {number}
             */
            this["physWidth"] = 0;
        }
        if (!("dpiScale" in $$source)) {
            /**
             * e.g. 1.25 at 125%
             * @member
             * @type {number}
             */
            this["dpiScale"] = 0;
        }
        if (!("isPrimary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPrimary"] = false;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("workTopOffset" in $$source)) {
            /**
             * WorkTopOffset is the number of points/pixels between the monitor's true
             * top edge (Top) and where the bar's *resting* top lives. On macOS this is
             * the menu bar height (the menu bar is non-removable and always above the
             * bar's window level), so the bar sits at Top + WorkTopOffset. On Windows
             * and Linux this is 0 — the bar occupies the very top of the monitor and
             * the existing AppBar mechanism reserves the strip. Used by the slide
             * animation target and the hover-detection hit box so they agree with
             * where DockToMonitor actually places the window.
             * @member
             * @type {number}
             */
            this["workTopOffset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MonitorInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorInfo(/** @type {Partial<MonitorInfo>} */($$parsedSource));
    }
}

/**
 * PushdownStats contains diagnostic information about macOS window pushdown.
 */
export class PushdownStats {
    /**
     * Creates a new PushdownStats instance.
     * @param {Partial<PushdownStats>} [$$source = {}] - The source object to create the PushdownStats.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("trusted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["trusted"] = false;
        }
        if (!("observedApps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["observedApps"] = 0;
        }
        if (!("pushesThisSession" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pushesThisSession"] = 0;
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PushdownStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PushdownStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PushdownStats(/** @type {Partial<PushdownStats>} */($$parsedSource));
    }
}
