// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountConfig {
    /**
     * Creates a new AccountConfig instance.
     * @param {Partial<AccountConfig>} [$$source = {}] - The source object to create the AccountConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountConfig(/** @type {Partial<AccountConfig>} */($$parsedSource));
    }
}

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("monitor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["monitor"] = 0;
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("opacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["opacity"] = 0;
        }
        if (!("refreshSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["refreshSeconds"] = 0;
        }
        if (!("barHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["barHeight"] = 0;
        }
        if (!("activeAccount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeAccount"] = 0;
        }
        if (!("accounts" in $$source)) {
            /**
             * @member
             * @type {AccountConfig[]}
             */
            this["accounts"] = [];
        }
        if (!("hotkeys" in $$source)) {
            /**
             * @member
             * @type {HotkeyConfig}
             */
            this["hotkeys"] = (new HotkeyConfig());
        }
        if (!("startWithWindows" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startWithWindows"] = false;
        }
        if (!("clickThrough" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clickThrough"] = false;
        }
        if (!("appBarMode" in $$source)) {
            /**
             * push apps down (AppBar API)
             * @member
             * @type {boolean}
             */
            this["appBarMode"] = false;
        }
        if (!("pinned" in $$source)) {
            /**
             * false = auto-hide on mouseleave, undocked
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (!("stations" in $$source)) {
            /**
             * @member
             * @type {StationConfig[]}
             */
            this["stations"] = [];
        }
        if (!("activeStation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeStation"] = 0;
        }
        if (!("radioVolume" in $$source)) {
            /**
             * 0..1, persisted
             * @member
             * @type {number}
             */
            this["radioVolume"] = 0;
        }
        if (!("features" in $$source)) {
            /**
             * which bar segments are enabled
             * @member
             * @type {FeatureConfig}
             */
            this["features"] = (new FeatureConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        const $$createField12_0 = $$createType4;
        const $$createField15_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField6_0($$parsedSource["accounts"]);
        }
        if ("hotkeys" in $$parsedSource) {
            $$parsedSource["hotkeys"] = $$createField7_0($$parsedSource["hotkeys"]);
        }
        if ("stations" in $$parsedSource) {
            $$parsedSource["stations"] = $$createField12_0($$parsedSource["stations"]);
        }
        if ("features" in $$parsedSource) {
            $$parsedSource["features"] = $$createField15_0($$parsedSource["features"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * FeatureConfig toggles which optional bar segments are active. Disabling a
 * feature hides its segment AND, where one exists, frees the backing resource
 * rather than merely hiding the UI — Radio is the notable case: when off, the
 * native audio engine (a long-lived background player process) is never started
 * / is torn down. The other flags are pure show/hide of a bar segment. All
 * default true (see Defaults); a missing/partial "features" object in an older
 * config keeps unspecified flags enabled because Load unmarshals over Defaults.
 */
export class FeatureConfig {
    /**
     * Creates a new FeatureConfig instance.
     * @param {Partial<FeatureConfig>} [$$source = {}] - The source object to create the FeatureConfig.
     */
    constructor($$source = {}) {
        if (!("radio" in $$source)) {
            /**
             * #seg-radio + native audio engine
             * @member
             * @type {boolean}
             */
            this["radio"] = false;
        }
        if (!("monitor" in $$source)) {
            /**
             * #seg-mon cycler
             * @member
             * @type {boolean}
             */
            this["monitor"] = false;
        }
        if (!("theme" in $$source)) {
            /**
             * #seg-theme cycler
             * @member
             * @type {boolean}
             */
            this["theme"] = false;
        }
        if (!("weeklyUsage" in $$source)) {
            /**
             * #seg-msgs + #seg-reset
             * @member
             * @type {boolean}
             */
            this["weeklyUsage"] = false;
        }
        if (!("hourlyUsage" in $$source)) {
            /**
             * #seg-hourly + #seg-hourly-reset
             * @member
             * @type {boolean}
             */
            this["hourlyUsage"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeatureConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureConfig(/** @type {Partial<FeatureConfig>} */($$parsedSource));
    }
}

export class HotkeyConfig {
    /**
     * Creates a new HotkeyConfig instance.
     * @param {Partial<HotkeyConfig>} [$$source = {}] - The source object to create the HotkeyConfig.
     */
    constructor($$source = {}) {
        if (!("cycleMonitor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cycleMonitor"] = "";
        }
        if (!("toggleClickThrough" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toggleClickThrough"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HotkeyConfig(/** @type {Partial<HotkeyConfig>} */($$parsedSource));
    }
}

/**
 * StationConfig is a named, ordered collection of YouTube items played as a
 * radio station, with a per-station shuffle toggle. Shuffle is driven from the
 * bar's shuffle button (not the settings editor) and persisted here so the
 * on/off state survives restarts.
 */
export class StationConfig {
    /**
     * Creates a new StationConfig instance.
     * @param {Partial<StationConfig>} [$$source = {}] - The source object to create the StationConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {StationItem[]}
             */
            this["items"] = [];
        }
        if (!("shuffle" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["shuffle"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StationConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StationConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new StationConfig(/** @type {Partial<StationConfig>} */($$parsedSource));
    }
}

/**
 * StationItem is one YouTube source in a station: a single video/livestream
 * (ID is the 11-char video id) or a playlist (ID is the list id).
 */
export class StationItem {
    /**
     * Creates a new StationItem instance.
     * @param {Partial<StationItem>} [$$source = {}] - The source object to create the StationItem.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {StationItemKind}
             */
            this["kind"] = StationItemKind.$zero;
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * original user input, for the editor
             * @member
             * @type {string | undefined}
             */
            this["raw"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StationItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StationItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StationItem(/** @type {Partial<StationItem>} */($$parsedSource));
    }
}

/**
 * StationItemKind classifies one entry in a radio station's collection. It is a
 * hint from URL parsing; the resolver is authoritative on live-vs-VOD (a
 * watch?v= with a non-empty HLS manifest is treated as a livestream).
 * @readonly
 * @enum {string}
 */
export const StationItemKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ItemVideo: "video",
    ItemPlaylist: "playlist",
    ItemLivestream: "livestream",
};

// Private type creation functions
const $$createType0 = AccountConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = HotkeyConfig.createFrom;
const $$createType3 = StationConfig.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = FeatureConfig.createFrom;
const $$createType6 = StationItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
