// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * PresetInfo is the lightweight view handed to the frontend dropdown.
 */
export class PresetInfo {
    /**
     * Creates a new PresetInfo instance.
     * @param {Partial<PresetInfo>} [$$source = {}] - The source object to create the PresetInfo.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresetInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetInfo(/** @type {Partial<PresetInfo>} */($$parsedSource));
    }
}
